import { useEffect,useRef,useState } from "react";
import { api, setSession } from "../../services/api";
import "./AuthPage.css";
export default function AuthPage({ navigate }) {
  const googleButton=useRef(null); const googleClientId=import.meta.env.VITE_GOOGLE_CLIENT_ID;
  const [mode,setMode]=useState("login"); const [form,setForm]=useState({displayName:"",identifier:"",email:"",mobile:"",password:""}); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  const update=(event)=>setForm(current=>({...current,[event.target.name]:event.target.value}));
  const submit=async(event)=>{event.preventDefault();setLoading(true);setError("");try{const body=mode==="login"?{identifier:form.identifier,password:form.password}:{displayName:form.displayName,email:form.email||null,mobile:form.mobile||null,password:form.password};const session=await api(`/auth/${mode}`,{method:"POST",body:JSON.stringify(body)});setSession(session);navigate(session.user.role==="ADMIN"?"/admin":"/");}catch(reason){setError(reason.message);}finally{setLoading(false);}};
  useEffect(()=>{if(!googleClientId)return undefined;const render=()=>{if(!window.google?.accounts?.id||!googleButton.current)return;window.google.accounts.id.initialize({client_id:googleClientId,callback:async response=>{setLoading(true);setError("");try{const session=await api("/auth/google",{method:"POST",body:JSON.stringify({credential:response.credential})});setSession(session);navigate(session.user.role==="ADMIN"?"/admin":"/");}catch(reason){setError(reason.message);}finally{setLoading(false);}}});googleButton.current.replaceChildren();window.google.accounts.id.renderButton(googleButton.current,{theme:"outline",size:"large",shape:"rectangular",width:366,text:mode==="login"?"signin_with":"signup_with"});};let script=document.querySelector('script[data-google-identity]');if(!script){script=document.createElement("script");script.src="https://accounts.google.com/gsi/client";script.async=true;script.dataset.googleIdentity="true";document.head.appendChild(script);}script.addEventListener("load",render);render();return()=>script.removeEventListener("load",render);},[googleClientId,mode,navigate]);
  return <main className="authPage"><section className="authCard"><small>ENGINEERING DECODED</small><h1>{mode==="login"?"Welcome back":"Create your account"}</h1><p>{mode==="login"?"Sign in with your email address or mobile number.":"Track lessons, completed courses, and learning progress."}</p>{googleClientId&&<><div className="googleButton" ref={googleButton}/><div className="authDivider"><span>or continue with credentials</span></div></>}<form onSubmit={submit}>{mode==="register"&&<><label>Display name<input name="displayName" value={form.displayName} onChange={update} required maxLength="120"/></label><label>Email<input name="email" type="email" value={form.email} onChange={update} placeholder="Email or mobile is required"/></label><label>Mobile<input name="mobile" value={form.mobile} onChange={update} placeholder="+919876543210"/></label></>}{mode==="login"&&<label>Email or mobile<input name="identifier" value={form.identifier} onChange={update} required autoComplete="username"/></label>}<label>Password<input name="password" type="password" value={form.password} onChange={update} required minLength="8" autoComplete={mode==="login"?"current-password":"new-password"}/></label>{error&&<div className="authError">{error}</div>}<button className="authSubmit" disabled={loading}>{loading?"Please wait…":mode==="login"?"Sign in":"Create account"}</button></form>{mode==="login"&&<button className="authSwitch" onClick={()=>navigate("/forgot-password")}>Forgot password?</button>}<button className="authSwitch" onClick={()=>{setMode(mode==="login"?"register":"login");setError("");}}>{mode==="login"?"New here? Create an account":"Already registered? Sign in"}</button></section></main>;
}
