import { useEffect, useState } from "react";
import { articleTemplates } from "../../data/catalog";
import { getArticleComponent } from "../articles/registry";
import "./ArticlePage.css";

function GenericArticle({track}){return <div className="genericArticle"><section id="overview"><p className="lead">This dedicated {track.name} article is ready for your technical content.</p><p>Create a new JSX component for this route when you are ready to write it. The shared reader, navigation, progress, and next-article behavior will continue to work automatically.</p></section><section id="concepts"><h2>1. Core concepts</h2><p>Document the stable mental models, terminology, constraints, and trade-offs that engineers need to understand.</p></section><section id="example"><h2>2. Practical example</h2><pre><code>{`// Add a focused ${track.name} example here\nconst lesson = { status: "ready" };`}</code></pre></section><section id="mistakes"><h2>3. Common mistakes</h2><p>Explain the failure modes that occur most often in real projects.</p></section><section id="check"><h2>4. Knowledge check</h2><div className="quiz"><p>When would you use {track.name}, and what alternative would you compare it with?</p></div></section></div>}

export default function ArticlePage({module,track,articleSlug,navigate}){
 const[progress,setProgress]=useState(0);const article=articleTemplates.find(item=>item.slug===articleSlug)||articleTemplates[0];
 useEffect(()=>{const update=()=>{const max=document.documentElement.scrollHeight-innerHeight;setProgress(max?Math.min(100,(scrollY/max)*100):0)};addEventListener("scroll",update);return()=>removeEventListener("scroll",update)},[]);
 if(!module||!track)return <main className="notFound"><h1>Article not found</h1><button onClick={()=>navigate("/")}>Back home</button></main>;
 const index=articleTemplates.findIndex(item=>item.slug===article.slug);const next=articleTemplates[index+1];const DedicatedArticle=getArticleComponent(module.id,track.slug,article.slug);
 return <main className="reader" style={{"--course-accent":module.accent}}><div className="readProgress" style={{width:`${progress}%`}}/><aside className="chapterNav"><button onClick={()=>navigate(`/learn/${module.id}/${track.slug}`)}>← Course overview</button><div><small>{module.name}</small><h2>{track.name}</h2><span>{index+1} / {articleTemplates.length} ARTICLES</span><i><b style={{width:`${((index+1)/articleTemplates.length)*100}%`}}/></i></div><nav>{articleTemplates.map((item,i)=><button className={item.slug===article.slug?"active":""} key={item.slug} onClick={()=>navigate(`/learn/${module.id}/${track.slug}/${item.slug}`)}><span>{i<index?"✓":String(i+1).padStart(2,"0")}</span><b>{item.title}</b></button>)}</nav></aside><article className="article"><header><div className="crumbs"><button onClick={()=>navigate(`/learn/${module.id}`)}>{module.name}</button><span>/</span><button onClick={()=>navigate(`/learn/${module.id}/${track.slug}`)}>{track.name}</button></div><h1>{article.title}</h1><div className="articleMeta"><span>◷ {article.time} read</span><span>◆ Updated Aug 2026</span><button>☆ SAVE</button></div></header>{DedicatedArticle?<DedicatedArticle/>:<GenericArticle track={track}/>} {next&&<button className="nextArticle" onClick={()=>navigate(`/learn/${module.id}/${track.slug}/${next.slug}`)}><span>NEXT ARTICLE</span><b>{next.title}</b><i>→</i></button>}</article><aside className="articleToc"><small>READING PROGRESS</small><i><b style={{width:`${progress}%`}}/></i><span>{Math.round(progress)}%</span><h3>On this page</h3><a href="#overview">Overview</a><a href="#concepts">Core concepts</a><a href="#example">Practical example</a><a href="#mistakes">Common mistakes</a><a href="#check">Knowledge check</a></aside></main>
}
